import { nextJsConfig } from "@repo/eslint-config/next-js";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...nextJsConfig,
  {
    // Generated by `msw init` — not our source, don't lint it.
    ignores: ["public/mockServiceWorker.js", "storybook-static/**"],
  },
];
